  name: nestjs-learning

  services:
    postgres:
      image: postgres:15-alpine
      container_name: nestjs-pg-hello
      environment:
        POSTGRES_USER: ${POSTGRES_USER} 
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
        POSTGRES_DB: ${POSTGRES_DB} 
        POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD} 
      ports:
        - "${POSTGRES_PORT:-5432}:5432"
      volumes:
        - ${PG_DATA_PATH}:/var/lib/postgresql/data
      restart: ${RESTART}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U nestjs -d nestjs_db"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 30s